name: Build Lambda Layer

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          mkdir -p layer/python
          pip install -r requirements.txt -t layer/python

      - name: Zip layer
        run: |
          cd layer
          zip -r ../python-docx-layer.zip python

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: python-docx-layer
          path: python-docx-layer.zip
